image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      cabal update
      stack build
  - name: Entangled daemon
    command: entangled daemon
    openMode: split-right
  - name: mkdocs serve
    command: mkdocs serve
    openMode: split-right

vscode:
  extensions:
    - haskell.haskell
    - dhall.dhall-lang
