# ~\~ language=YAML filename=mkdocs.yml
# ~\~ begin <<docs/index.md|mkdocs.yml>>[0]
site_name: Entangled and MkDocs
nav:
        - Home: "index.md"
        - About: "about.md"
        - Experiments: "syntax_experiments.md"
        - Deployment: "deployment.md"
site_url: https://entangled.github.io/mkdocs
repo_url: https://github.com/entangled/mkdocs
site_description: >
        Setup an MkDocs project that works with Entangled for Literate Programming.
site_author: Johan Hidding
copyright: "<a href=\"https://esciencecenter.nl/\">Netherlands eScience Center</a>"
# ~\~ end
# ~\~ begin <<docs/index.md|mkdocs.yml>>[1]
# ~\~ begin <<docs/index.md|theme>>[0]
theme:
        name: material
# ~\~ end

markdown_extensions:
        # ~\~ begin <<docs/index.md|markdown-extensions>>[0]
        - pymdownx.highlight:
            anchor_linenums: true
        - pymdownx.inlinehilite
        - pymdownx.snippets
        - pymdownx.superfences
        # ~\~ end
        # ~\~ begin <<docs/index.md|markdown-extensions>>[1]
        - pymdownx.arithmatex
        # ~\~ end
        - admonition
        - toc:
            permalink: true

extra_css:
        # ~\~ begin <<docs/index.md|extra-css>>[0]

        # ~\~ end

extra_javascript:
        # ~\~ begin <<docs/index.md|extra-javascript>>[0]
        - "https://polyfill.io/v3/polyfill.min.js?features=es6"
        - "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
        # ~\~ end
# ~\~ end
