# ~\~ language=YAML filename=.github/workflows/ci.yml
# ~\~ begin <<docs/deployment.md|.github/workflows/ci.yml>>[0]
name: ci # (1)!
on:
  push:
    branches: # (2)!
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # ~\~ begin <<docs/deployment.md|tangle_code_files>>[0]
      - run: pip install entangled-filters
      - run: wget https://github.com/entangled/entangled/releases/download/v1.2.4/entangled-1.2.4-x86_64-GNU-Linux.tar.xz && tar --extract --file entangled-1.2.4-x86_64-GNU-Linux.tar.xz && sudo cp -r ./entangled-1.2.4/* /usr/local/
      - run: entangled tangle -a
      # ~\~ end
      # ~\~ begin <<docs/deployment.md|weave_mkdocs_site>>[0]
      - run: pip install mkdocs-material # (3)!
      - run: mkdocs gh-deploy --force
      # ~\~ end

# ~\~ end
